# Generated by Django 3.2.9 on 2021-12-03 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_alter_aluno_options'),
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name': 'Matrícula de Aluno', 'verbose_name_plural': 'Matrículas de Aluno'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='nome_aluno',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comum_aluno', to='comum.aluno', verbose_name='Aluno'),
            preserve_default=False,
        ),
    ]
