# Generated by Django 3.2.9 on 2021-12-03 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_auto_20211203_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edu_curso', to='edu.curso', verbose_name='Curso'),
        ),
    ]
